spring.application.name=RCU

spring.datasource.url=jdbc:postgresql://localhost:5432/mi_base_de_datos
spring.datasource.username=mi_usuario
spring.datasource.password=mi_contraseña
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#configuración de seguridad, en un producto serio no dejar el secret a la vista, usar variables de entorno o un vault
security.jwt.secret=falseSecret
security.jwt.expiration-seconds=3600
spring.jackson.serialization.write-dates-as-timestamps: false